name: the coding wharf
markdown: kramdown
site.baseurl: "cchanzl.github.io"
permalink: /:categories/:year/:month/:day/:title
kramdown:
  input: GFM
  syntax_highlighter: rouge
theme: jekyll-theme-cayman
